import { historyCancelFlow } from "./history-cancel-flow";
import { applyLeaveFlow } from "./leave-flow";
import { test, expect } from "../../frontend/node_modules/@playwright/test";
import { addDays, format, parseISO } from "../../frontend/node_modules/date-fns";
test("holiday calendar, apply, history and cancellation transactions",async({page,request})=>{
  const errors: string[]=[];page.on("pageerror",error=>errors.push(error.message));
  await page.goto("/login");await page.getByLabel("Email or Employee ID *").fill("EMP001");
  await page.getByLabel("Password *",{exact:true}).fill(process.env.E2E_TEST_PASSWORD!);
  await page.getByRole("button",{name:"Sign in",exact:true}).click();await expect(page).toHaveURL(/\/dashboard$/);
  const stored=await page.evaluate(()=>JSON.parse(sessionStorage.getItem("aip-lms-session")!));
  const headers={Authorization:`Bearer ${stored.token}`};const origin=process.env.E2E_API_URL;
  const identity=await (await request.get(`${origin}/api/v1/auth/me`,{headers})).json();
  const year=Number(identity.business_today.slice(0,4));
  await page.getByRole("navigation").getByRole("link",{name:"Holidays",exact:true}).click();
  await expect(page.getByRole("heading",{name:"Holiday Calendar"})).toBeVisible();
  await page.getByLabel("Month",{exact:true}).selectOption("1");
  await expect(page).toHaveURL(new RegExp(`year=${year}&month=1`));
  const holiday=page.getByRole("button",{name:/Example New Year Holiday, Mandatory/});await expect(holiday).toBeVisible();
  await holiday.focus();await page.keyboard.press("Enter");await expect(page.getByRole("region",{name:"Holiday details"})).toContainText("Example New Year Holiday");
  await page.screenshot({path:"../.cache/phase5-calendar.png",fullPage:true});
  await page.getByRole("button",{name:"Close details"}).click();await page.getByRole("button",{name:"List",exact:true}).click();
  await expect(page.getByRole("table")).toContainText("Example New Year Holiday");
  await page.screenshot({path:"../.cache/phase5-holiday-list.png",fullPage:true});
  await page.setViewportSize({width:390,height:844});await page.reload();
  await expect(page.getByRole("button",{name:"List",exact:true})).toHaveAttribute("aria-pressed","true");
  await expect(page.getByRole("heading",{name:"Example New Year Holiday"})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.screenshot({path:"../.cache/phase5-holidays-mobile.png",fullPage:true});
  const types=await (await request.get(`${origin}/api/v1/leave-types`,{headers})).json();
  let start=parseISO(identity.business_today);while(start.getDay()!==6) start=addDays(start,1);
  if(start.getFullYear()!==addDays(start,1).getFullYear()) start=addDays(start,7);
  const body={employee_id:identity.employee_id,leave_type_id:types.items[0].leave_type_id,from_date:format(start,"yyyy-MM-dd"),to_date:format(addDays(start,1),"yyyy-MM-dd")};
  const before=await (await request.get(`${origin}/api/v1/employees/${identity.employee_id}/leave-balance`,{headers})).json();
  const preview=await request.post(`${origin}/api/v1/leave/calculate-days`,{headers,data:body});expect(preview.status()).toBe(200);
  expect(await preview.json()).toEqual({from_date:body.from_date,to_date:body.to_date,calendar_days:2,weekend_days:2,holiday_days:0,leave_days:0});
  const after=await (await request.get(`${origin}/api/v1/employees/${identity.employee_id}/leave-balance`,{headers})).json();expect(after).toEqual(before);
  const applied=await applyLeaveFlow(page,request,identity,headers);await historyCancelFlow(page,request,identity,headers,applied);expect(errors).toEqual([]);
});
