"use client";
import { useEffect, useState, useSyncExternalStore } from "react";
import { useAuth } from "@/hooks/use-auth";
import { useHolidayFilters } from "@/hooks/use-holiday-filters";
import { useAdminHolidays } from "@/hooks/use-admin-holidays";
import { QueryError, QueryLoading } from "@/components/common/QueryState";
import { YearSelect } from "@/components/common/YearSelect";
import { HolidayCalendar } from "./HolidayCalendar";
import { HolidayDialog } from "./HolidayDialog";
import { calendarDate } from "@/lib/format";
import type { Holiday } from "@/types/employee";
function subscribe(callback: () => void) { const media = window.matchMedia?.("(max-width: 767px)"); media?.addEventListener("change", callback); return () => media?.removeEventListener("change", callback); }
function mobileSnapshot() { return window.matchMedia?.("(max-width: 767px)").matches ?? false; }
type DialogState = { kind: "create" } | { kind: "edit" | "toggle"; row: Holiday };
export function AdminHolidayScreen() {
  const { user } = useAuth(); const filters = useHolidayFilters(); const query = useAdminHolidays(filters.valid ? filters.year : null, filters.inactive);
  const mobile = useSyncExternalStore(subscribe, mobileSnapshot, () => true);
  const view = filters.view ?? (mobile ? "list" : "calendar"); const [dialog, setDialog] = useState<DialogState | null>(null); const [notice, setNotice] = useState("");
  useEffect(() => { document.title = "Holiday Management · Employee Leave Management"; }, []);
  const all = query.data?.items ?? []; const shown = filters.month === null ? all : all.filter(row => Number(row.holiday_date.slice(5,7)) === filters.month);
  function actions(row: Holiday) { return <div className="flex flex-wrap gap-2"><button onClick={() => setDialog({ kind: "edit", row })} className="min-h-11 rounded border px-3 py-2">Edit {row.name}</button><button onClick={() => setDialog({ kind: "toggle", row })} className="min-h-11 rounded border px-3 py-2">{row.status === "ACTIVE" ? "Deactivate" : "Activate"} {row.name}</button></div>; }
  return <section className="max-w-6xl space-y-5"><header className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-3xl font-semibold">Holiday Management</h1><button onClick={() => setDialog({ kind: "create" })} className="min-h-11 rounded bg-blue-700 px-4 py-2 text-white">Add Holiday</button></header><p className="text-sm text-slate-600">Changes apply to future leave-day calculations. Existing applications keep their stored days.</p>
    <div className="flex flex-wrap items-center gap-4 [&_select]:min-h-11"><YearSelect year={filters.valid ? filters.year : null} options={filters.options} select={year => filters.update({ year: String(year) })}/><label className="flex min-h-11 items-center gap-3"><input type="checkbox" role="switch" checked={filters.inactive} onChange={event => filters.update({ inactive: event.target.checked ? "true" : null })}/>Show inactive</label><label>Month<select value={filters.month ?? ""} onChange={event => filters.update({ month: event.target.value || null })} className="ml-2 rounded border p-2"><option value="">All months</option>{Array.from({ length: 12 }, (_,i) => <option key={i+1} value={i+1}>{new Intl.DateTimeFormat("en", { month: "long", timeZone: "UTC" }).format(new Date(Date.UTC(2026,i,1)))}</option>)}</select></label></div>
    <div role="group" aria-label="Holiday view" className="flex flex-wrap gap-2">{(["calendar", "list"] as const).map(option => <button key={option} aria-pressed={view === option} onClick={() => filters.update({ view: option })} className={`min-h-11 rounded border px-4 py-2 ${view === option ? "border-blue-600 bg-blue-50 text-blue-800" : "bg-white"}`}>{option === "calendar" ? "Calendar" : "List"}</button>)}<button onClick={filters.clear} className="min-h-11 px-3 text-blue-700 underline">Clear filters</button></div>
    {notice && <p role="status">{notice}</p>}
    {!filters.valid ? <p role="alert">Invalid holiday filters. Clear filters to continue.</p> : query.isPending ? <QueryLoading/> : query.isError ? <QueryError error={query.error} retry={() => void query.refetch()}/> : <>
      {query.isFetching && <p role="status">Refreshing holidays…</p>}{!shown.length && <p>No holidays match these filters.</p>}
      {view === "calendar" ? <div className="[&_button]:min-h-11"><HolidayCalendar year={filters.year} month={filters.month ?? Number(user?.business_today.slice(5,7))} today={user?.business_today ?? ""} holidays={all} showStatus select={row => setDialog({ kind: "edit", row })} navigate={(year,month) => filters.update({ year: String(year), month: String(month) })}/><p className="mt-3 text-sm text-slate-600">Select a holiday to edit its details. Inactive holidays do not reduce leave days.</p></div> : shown.length > 0 && <><div className="hidden overflow-x-auto rounded border bg-white md:block"><table className="w-full text-left text-sm"><caption className="sr-only">Managed holidays</caption><thead><tr>{["Holiday", "Date", "Type", "Description", "Status", "Actions"].map(name => <th key={name} scope="col" className="p-3">{name}</th>)}</tr></thead><tbody>{shown.map(row => <tr key={row.holiday_id} className="border-t"><th scope="row" className="max-w-xs break-words p-3 font-medium">{row.name}</th><td className="whitespace-nowrap p-3">{calendarDate(row.holiday_date)}</td><td className="p-3">{row.is_optional ? "Optional" : "Mandatory"}</td><td className="max-w-sm break-words p-3">{row.description ?? "—"}</td><td className="p-3">{row.status === "ACTIVE" ? "Active" : "Inactive"}</td><td className="p-3">{actions(row)}</td></tr>)}</tbody></table></div><div className="space-y-3 md:hidden">{shown.map(row => <article key={row.holiday_id} aria-label={row.name} className="space-y-3 rounded border bg-white p-4"><h2 className="break-words font-semibold">{row.name}</h2><p>{calendarDate(row.holiday_date)} · {row.is_optional ? "Optional" : "Mandatory"}</p><p className="break-words">{row.description ?? "No description provided."}</p><p>{row.status === "ACTIVE" ? "Active" : "Inactive"}</p>{actions(row)}</article>)}</div></>}
    </>}
    {dialog && <HolidayDialog kind={dialog.kind} row={"row" in dialog ? dialog.row : undefined} close={() => { setDialog(null); void query.refetch(); }} success={(row,message) => { setDialog(null); setNotice(message); if (row.year >= 1900 && row.year <= 9999) filters.update({ year: String(row.year), month: null }); }}/>}</section>;
}
