import Link from "next/link";
import { calendarDay, eventTime, leaveDays } from "@/lib/format";
import { StatusBadge } from "@/features/leave/StatusBadge";
import type { ApplicationRow } from "@/types/employee";
export function ApplicationReportTable({ items, timezone }: { items: ApplicationRow[]; timezone: string }) {
  const link = (row: ApplicationRow) => <Link href={`/leave/applications/${row.application_id}`} className="inline-flex min-h-11 items-center break-all font-mono text-blue-700 underline" aria-label={`View application ${row.application_id}`}>{row.application_id}</Link>;
  return <><div className="hidden overflow-x-auto rounded border bg-white md:block"><p className="p-3 text-xs text-slate-600">Scroll horizontally to view all application columns.</p><table className="w-full text-left text-sm"><caption className="sr-only">Leave application report</caption><thead><tr>{["Application ID", "Employee", "Leave Type", "From", "To", "Days", "Status", "Applied Date", "Manager"].map(label => <th key={label} scope="col" className="p-3">{label}</th>)}</tr></thead><tbody>{items.map(row => <tr key={row.application_id} className="border-t"><td className="min-w-40 p-3">{link(row)}</td><th scope="row" className="p-3 font-medium">{row.employee_name}<span className="block text-xs text-slate-600">{row.employee_code}</span></th><td className="p-3">{row.leave_type_name}</td><td className="whitespace-nowrap p-3">{calendarDay(row.from_date)}</td><td className="whitespace-nowrap p-3">{calendarDay(row.to_date)}</td><td className="p-3">{leaveDays(row.number_of_days)}</td><td className="p-3"><StatusBadge status={row.status}/></td><td className="p-3">{eventTime(row.created_at, timezone)}</td><td className="p-3">{row.manager.name} ({row.manager.employee_code})</td></tr>)}</tbody></table></div>
    <div className="space-y-3 md:hidden">{items.map(row => <article key={row.application_id} className="space-y-3 rounded border bg-white p-4"><h3 className="break-words font-semibold">{row.employee_name} ({row.employee_code})</h3><p>{row.leave_type_name}</p>{link(row)}<dl className="space-y-2"><div><dt className="text-sm text-slate-600">Period</dt><dd>{calendarDay(row.from_date)} – {calendarDay(row.to_date)}</dd></div><div><dt className="text-sm text-slate-600">Days</dt><dd>{leaveDays(row.number_of_days)}</dd></div><div><dt className="text-sm text-slate-600">Applied Date</dt><dd>{eventTime(row.created_at, timezone)}</dd></div><div><dt className="text-sm text-slate-600">Manager</dt><dd>{row.manager.name} ({row.manager.employee_code})</dd></div></dl><StatusBadge status={row.status}/></article>)}</div>
  </>;
}
