import { render, screen, within, waitFor, fireEvent } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { http, HttpResponse } from "msw";
import { beforeAll, afterEach, describe, it, expect, vi } from "vitest";
import { AuthProvider } from "@/features/auth/AuthProvider";
import { AuthGate } from "@/features/auth/AuthGate";
import { LeaveBalancesScreen } from "@/features/leave-balances/LeaveBalancesScreen";
import { SESSION_KEY } from "@/hooks/use-auth-session";
import { safeReturnTo } from "@/lib/permissions";
import type { Identity } from "@/types/auth";
import type { Employee, LeaveType } from "@/types/employee";
import type { BalanceRow } from "@/types/admin-balance";
import { server } from "./mocks/server";
import { navigationMock } from "./navigation-mock";
const base = "http://localhost:18000/api/v1";
const employeeId = "11111111-1111-4111-8111-111111111111", typeId = "22222222-2222-4222-8222-222222222222", freeId = "33333333-3333-4333-8333-333333333333", balanceId = "44444444-4444-4444-8444-444444444444", departmentId = "55555555-5555-4555-8555-555555555555";
const department = { department_id: departmentId, code: "ENG", name: "Engineering" };
const identity: Identity = { user_id: "admin-user", employee_id: employeeId, employee_code: "ADM001", name: "Administrator", email: "admin@example.invalid", role: "ADMINISTRATOR", department, organization_timezone: "Asia/Kolkata", business_today: "2026-10-10" };
const employee: Employee = { employee_id: employeeId, employee_code: "EMP001", name: "Example Employee", department, manager: null, status: "INACTIVE", email: "employee@example.invalid", phone: null, designation: null, joining_date: "2020-01-01" };
const row: BalanceRow = { balance_id: balanceId, employee_id: employeeId, leave_type_id: typeId, leave_year: 2026, employee, department, leave_type: { leave_type_id: typeId, code: "EARNED", name: "Earned Leave" }, allocated: 10, carried_forward: 2, used: 3, pending: 2, available: 7 };
const type: LeaveType = { leave_type_id: typeId, code: "EARNED", name: "Earned Leave", description: null, is_paid: true, allow_employee_application: true, allow_half_day: false, requires_approval: true, status: "ACTIVE" };
const freeType: LeaveType = { ...type, leave_type_id: freeId, code: "CUSTOM", name: "Custom Leave", status: "INACTIVE", allow_employee_application: false };
const selected = `/admin/leave-balances?employee_id=${employeeId}`;
function page(items = [row], total = items.length) { return { items, page: 1, page_size: 20, total }; }
function failure(status = 500, code = "TRANSACTION_FAILED", details: unknown = null) { return HttpResponse.json({ error: { code, message: "private SQL password", details } }, { status }); }
function mount(path = "/admin/leave-balances", role: Identity["role"] = "ADMINISTRATOR", items = [row]) {
  window.history.replaceState({}, "", path); navigationMock.pathname = path.split("?")[0];
  sessionStorage.setItem(SESSION_KEY, JSON.stringify({ token: "test-token", expires_at: Date.now() + 60_000 }));
  server.use(http.get(`${base}/auth/me`, () => HttpResponse.json({ ...identity, role })), http.get(`${base}/admin/leave-balances`, () => HttpResponse.json(page(items))), http.get(`${base}/employees/${employeeId}`, () => HttpResponse.json(employee)), http.get(`${base}/employees`, () => HttpResponse.json({ items: [employee], page: 1, page_size: 20, total: 1 })), http.get(`${base}/departments`, () => HttpResponse.json({ items: [department] })), http.get(`${base}/leave-types`, () => HttpResponse.json({ items: [type, freeType] })), http.get(`${base}/employees/${employeeId}/leave-balance`, ({ request }) => HttpResponse.json({ employee_id: employeeId, employee_code: "EMP001", year: Number(new URL(request.url).searchParams.get("year")), balances: new URL(request.url).searchParams.get("year") === "2026" ? [{ ...row, leave_type: "EARNED", leave_type_name: "Earned Leave" }] : [] })));
  const client = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } });
  render(<QueryClientProvider client={client}><AuthProvider><AuthGate><LeaveBalancesScreen/></AuthGate></AuthProvider></QueryClientProvider>); return client;
}
beforeAll(() => { Object.defineProperty(HTMLDialogElement.prototype, "showModal", { configurable: true, value: function(this: HTMLDialogElement) { this.setAttribute("open", ""); } }); Object.defineProperty(HTMLDialogElement.prototype, "close", { configurable: true, value: function(this: HTMLDialogElement) { this.removeAttribute("open"); } }); });
afterEach(() => vi.restoreAllMocks());
async function open(kind: "edit" | "adjust") { await userEvent.click(within(await screen.findByRole("table")).getByRole("button", { name: kind === "edit" ? "Edit allocation" : "Adjust balance" })); return screen.getByRole("dialog"); }
async function allocate() { const button = await screen.findByRole("button", { name: "Allocate Leave" }); await waitFor(() => expect(button).toBeEnabled()); await userEvent.click(button); const dialog = screen.getByRole("dialog"); await waitFor(() => expect(within(dialog).getByLabelText("Leave Type *")).toBeEnabled()); await userEvent.selectOptions(within(dialog).getByLabelText("Leave Type *"), freeId); change(dialog, "Allocated *", "10.25"); return dialog; }
function change(dialog: HTMLElement, label: string, value: string) { fireEvent.change(within(dialog).getByLabelText(label), { target: { value } }); }
async function save(dialog: HTMLElement, adjust = false) { await userEvent.click(within(dialog).getByRole("button", { name: adjust ? "Save Adjustment" : "Save Allocation" })); }
describe("Phase 13 balance administration", () => {
  it.each(["EMPLOYEE", "MANAGER"] as const)("denies %s", async role => { mount("/admin/leave-balances", role); expect(await screen.findByText("You don't have permission to view this page.")).toBeVisible(); expect(screen.queryByRole("table")).not.toBeInTheDocument(); });
  it("shows all counters, historical context and mobile cards", async () => { mount(); const table = await screen.findByRole("table", { name: "Organization leave balances" }); for (const name of ["Allocated", "Carried Forward", "Used", "Pending", "Available"]) expect(within(table).getByRole("columnheader", { name })).toBeVisible(); expect(within(table).getByText("7.00")).toBeVisible(); expect(screen.getByRole("article")).toHaveTextContent("Pending2.00"); expect(screen.getByLabelText("Year")).toHaveValue("2026"); expect(screen.getByRole("button", { name: "Allocate Leave" })).toBeDisabled(); });
  it("restores conjunctive filters and resets pagination on changes", async () => { let query = ""; mount(`${selected}&year=2025&department_id=${departmentId}&leave_type_id=${typeId}&page=2&page_size=10`); server.use(http.get(`${base}/admin/leave-balances`, ({ request }) => { query = new URL(request.url).search; return HttpResponse.json(page([row], 30)); })); await screen.findByRole("table"); expect(query).toContain("year=2025"); expect(query).toContain(`employee_id=${employeeId}`); expect(screen.getByLabelText("Year")).toHaveValue("2025"); fireEvent.change(screen.getByLabelText("Year"), { target: { value: "2024" } }); fireEvent.blur(screen.getByLabelText("Year")); expect(navigationMock.replace).toHaveBeenCalledWith(expect.stringContaining("year=2024"), { scroll: false }); expect(navigationMock.replace.mock.calls.at(-1)![0]).not.toContain("page=2"); await userEvent.selectOptions(screen.getByLabelText("Department"), ""); expect(navigationMock.replace.mock.calls.at(-1)![0]).toContain("year=2024"); expect(navigationMock.replace.mock.calls.at(-1)![0]).not.toContain("department_id"); });
  it.each(["year=1899", "year=2026&year=2025", "employee_id=bad", "department_id=", "leave_type_id=bad", "page=0", "page_size=101", "unexpected=1"])("blocks invalid %s without balance reads", async query => { let calls = 0; mount(`/admin/leave-balances?${query}`); server.use(http.get(`${base}/admin/leave-balances`, () => { calls++; return HttpResponse.json(page()); })); expect(await screen.findByRole("alert")).toHaveTextContent("Invalid balance filters"); expect(calls).toBe(0); await userEvent.click(screen.getByRole("button", { name: "Clear filters" })); expect(navigationMock.replace).toHaveBeenCalledWith("/admin/leave-balances", { scroll: false }); });
  it("shows list loading, safe errors, retry and empty state", async () => { mount(); let release!: () => void; const pending = new Promise<void>(resolve => { release = resolve; }); server.use(http.get(`${base}/admin/leave-balances`, async () => { await pending; return failure(); })); expect(await screen.findByText("Loading your information…")).toBeVisible(); release(); expect(await screen.findByRole("alert")).not.toHaveTextContent("private"); server.use(http.get(`${base}/admin/leave-balances`, () => HttpResponse.json(page([])))); await userEvent.click(screen.getByRole("button", { name: "Retry" })); expect(await screen.findByText("No leave balances match these filters.")).toBeVisible(); });
  it("allocates numeric fields for the selected employee and excludes existing types", async () => { const client = mount(selected); const invalidate = vi.spyOn(client, "invalidateQueries"); let body: unknown; server.use(http.post(`${base}/admin/leave-balances`, async ({ request }) => { body = await request.json(); return HttpResponse.json(row, { status: 201 }); })); const dialog = await allocate(); expect(within(dialog).queryByRole("option", { name: "Earned Leave (EARNED)" })).not.toBeInTheDocument(); expect(within(dialog).getByRole("option", { name: "Custom Leave (CUSTOM) — inactive" })).toBeInTheDocument(); await save(dialog); expect(await screen.findByText("Balance saved. Allocated: 10.00; Available: 7.00.")).toBeVisible(); expect(body).toEqual({ employee_id: employeeId, leave_type_id: freeId, leave_year: 2026, allocated: 10.25, carried_forward: 0 }); for (const key of ["admin-balances", "balances", "dashboard", "leave-preview"]) expect(invalidate).toHaveBeenCalledWith({ queryKey: [key] }); });
  it("reloads allocation eligibility when changing to a historical year", async () => { mount(selected); const dialog = await allocate(); change(dialog, "Year *", "2025"); await waitFor(() => expect(within(dialog).getByRole("option", { name: "Earned Leave (EARNED)" })).toBeInTheDocument()); await waitFor(() => expect(within(dialog).getByLabelText("Leave Type *")).toBeEnabled()); });
  it("blocks allocation when all types already have balances", async () => { mount(selected); server.use(http.get(`${base}/leave-types`, () => HttpResponse.json({ items: [type] }))); const button = await screen.findByRole("button", { name: "Allocate Leave" }); await waitFor(() => expect(button).toBeEnabled()); await userEvent.click(button); expect(await screen.findByText("No leave types without an allocation are available for this employee and year.")).toBeVisible(); expect(screen.getByRole("button", { name: "Save Allocation" })).toBeDisabled(); });
  it("blocks allocation on lookup failure and recovers on retry", async () => { mount(selected); server.use(http.get(`${base}/employees/${employeeId}/leave-balance`, () => failure())); const button = await screen.findByRole("button", { name: "Allocate Leave" }); await waitFor(() => expect(button).toBeEnabled()); await userEvent.click(button); const dialog = screen.getByRole("dialog"); expect(await within(dialog).findByRole("alert")).not.toHaveTextContent("private"); expect(within(dialog).getByRole("button", { name: "Save Allocation" })).toBeDisabled(); server.use(http.get(`${base}/employees/${employeeId}/leave-balance`, () => HttpResponse.json({ employee_id: employeeId, year: 2026, balances: [] }))); await userEvent.click(within(dialog).getByRole("button", { name: "Retry" })); await waitFor(() => expect(within(dialog).getByLabelText("Leave Type *")).toBeEnabled()); });
  it("edits only entitlement counters and preserves read-only workflow counters", async () => { mount(); let body: unknown; server.use(http.put(`${base}/admin/leave-balances/${balanceId}`, async ({ request }) => { body = await request.json(); return HttpResponse.json({ ...row, allocated: 12.5, available: 9.5 }); })); const dialog = await open("edit"); expect(within(dialog).getByText(/Used: 3.00; Pending: 2.00/)).toBeVisible(); expect(within(dialog).getByLabelText("Allocated *")).toHaveValue("10.00"); expect(within(dialog).queryByLabelText("Used")).not.toBeInTheDocument(); change(dialog, "Allocated *", "12.50"); await save(dialog); await screen.findByText("Balance saved. Allocated: 12.50; Available: 9.50."); expect(body).toEqual({ allocated: 12.5, carried_forward: 2 }); });
  it.each(["-1", "1.001", "100000000", "abc"])("rejects allocation %s locally", async value => { mount(); let calls = 0; server.use(http.put(`${base}/admin/leave-balances/${balanceId}`, () => { calls++; return HttpResponse.json(row); })); const dialog = await open("edit"); change(dialog, "Allocated *", value); await save(dialog); await waitFor(() => expect(within(dialog).getByLabelText("Allocated *")).toHaveAttribute("aria-invalid", "true")); expect(calls).toBe(0); });
  it("adjusts with trimmed reason, advisory arithmetic and authoritative returned counters", async () => { mount(); let body: unknown; server.use(http.post(`${base}/admin/leave-balances/${balanceId}/adjust`, async ({ request }) => { body = await request.json(); return HttpResponse.json({ balance_id: balanceId, adjustment: -1.25, reason: "Correction", new_allocated: 20, available: 17 }); })); const dialog = await open("adjust"); change(dialog, "Adjustment *", "-1.25"); change(dialog, "Reason *", " Correction "); expect(within(dialog).getByText(/New allocated = 8.75/)).toBeVisible(); await save(dialog, true); await screen.findByText("Balance saved. Allocated: 20.00; Available: 17.00."); expect(body).toEqual({ adjustment: -1.25, reason: "Correction" }); });
  it.each([["0", "valid", "Adjustment *"], ["1.001", "valid", "Adjustment *"], ["1", "  ", "Reason *"], ["1", "x".repeat(1001), "Reason *"]])("validates adjustment %s before writes", async (value, reason, field) => { mount(); let calls = 0; server.use(http.post(`${base}/admin/leave-balances/${balanceId}/adjust`, () => { calls++; return HttpResponse.json({}); })); const dialog = await open("adjust"); change(dialog, "Adjustment *", value); change(dialog, "Reason *", reason); await save(dialog, true); await waitFor(() => expect(within(dialog).getByLabelText(field)).toHaveAttribute("aria-invalid", "true")); expect(calls).toBe(0); });
  it("shows safe allocation errors without blocking corrected retries", async () => { mount(); server.use(http.put(`${base}/admin/leave-balances/${balanceId}`, () => failure(400, "INSUFFICIENT_ALLOCATION"))); const dialog = await open("edit"); await save(dialog); expect(await within(dialog).findByRole("alert")).not.toHaveTextContent("private"); expect(within(dialog).getByRole("button", { name: "Save Allocation" })).toBeEnabled(); });
  it("maps duplicate allocation to leave type and refreshes eligibility", async () => { mount(selected); server.use(http.post(`${base}/admin/leave-balances`, () => failure(409, "LEAVE_BALANCE_ALREADY_EXISTS"))); const dialog = await allocate(); await save(dialog); await waitFor(() => expect(within(dialog).getByLabelText("Leave Type *")).toHaveAttribute("aria-invalid", "true")); expect(within(dialog).getByRole("alert")).not.toHaveTextContent("private"); });
  it("maps backend validation details to the field", async () => { mount(); server.use(http.put(`${base}/admin/leave-balances/${balanceId}`, () => failure(422, "VALIDATION_ERROR", [{ field: "body.allocated" }]))); const dialog = await open("edit"); await save(dialog); await waitFor(() => expect(within(dialog).getByLabelText("Allocated *")).toHaveAttribute("aria-invalid", "true")); });
  it.each(["server", "network", "malformed"])("prevents repeating an uncertain %s adjustment", async mode => { mount(); let calls = 0; server.use(http.post(`${base}/admin/leave-balances/${balanceId}/adjust`, () => { calls++; return mode === "server" ? failure() : mode === "network" ? HttpResponse.error() : new HttpResponse("broken", { status: 200, headers: { "Content-Type": "application/json" } }); })); const dialog = await open("adjust"); change(dialog, "Adjustment *", "1"); change(dialog, "Reason *", "Correction"); await userEvent.dblClick(within(dialog).getByRole("button", { name: "Save Adjustment" })); expect(await screen.findByText(/The outcome is uncertain/)).toBeVisible(); expect(within(dialog).getByRole("button", { name: "Save Adjustment" })).toBeDisabled(); expect(calls).toBe(1); });
  it("confirms dirty cancellation, traps focus and restores the opener", async () => { mount(); const confirm = vi.spyOn(window, "confirm").mockReturnValue(false); const dialog = await open("edit"); const button = within(dialog).getByRole("button", { name: "Save Allocation" }); button.focus(); await userEvent.tab(); expect(within(dialog).getByLabelText("Allocated *")).toHaveFocus(); await userEvent.tab({ shift: true }); expect(button).toHaveFocus(); change(dialog, "Allocated *", "12"); fireEvent(dialog, new Event("cancel", { cancelable: true })); expect(dialog).toBeVisible(); confirm.mockReturnValue(true); await userEvent.click(within(dialog).getByRole("button", { name: "Cancel" })); expect(screen.queryByRole("dialog")).not.toBeInTheDocument(); expect(within(screen.getByRole("table")).getByRole("button", { name: "Edit allocation" })).toHaveFocus(); });
  it("allows administrator return paths only", () => { expect(safeReturnTo(selected, "ADMINISTRATOR")).toBe(selected); expect(safeReturnTo(selected, "MANAGER")).toBe("/dashboard"); });
});
