import { render, screen, within, waitFor, fireEvent } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { http, HttpResponse } from "msw";
import { afterEach, beforeAll, describe, it, expect, vi } from "vitest";
import { AuthProvider } from "@/features/auth/AuthProvider";
import { AuthGate } from "@/features/auth/AuthGate";
import { LeaveTypesScreen } from "@/features/leave-types/LeaveTypesScreen";
import { SESSION_KEY } from "@/hooks/use-auth-session";
import { safeReturnTo } from "@/lib/permissions";
import type { Identity } from "@/types/auth";
import type { LeaveType } from "@/types/employee";
import { leaveTypeUpdate } from "@/types/admin-leave-type";
import { server } from "./mocks/server";
import { navigationMock } from "./navigation-mock";
const base = "http://localhost:18000/api/v1", id = "11111111-1111-4111-8111-111111111111";
const identity: Identity = { user_id: "admin-user", employee_id: id, employee_code: "ADM001", name: "Administrator", email: "admin@example.invalid", role: "ADMINISTRATOR", department: { department_id: id, code: "ENG", name: "Engineering" }, organization_timezone: "Asia/Kolkata", business_today: "2026-10-09" };
const row: LeaveType = { leave_type_id: id, code: "CUSTOM", name: "Custom Leave", description: "Description", is_paid: true, allow_employee_application: true, allow_half_day: false, requires_approval: true, status: "ACTIVE" };
function failure(status = 500, code = "TRANSACTION_FAILED") { return HttpResponse.json({ error: { code, message: "private SQL password", details: null } }, { status }); }
beforeAll(() => {
  Object.defineProperty(HTMLDialogElement.prototype, "showModal", { configurable: true, value: function(this: HTMLDialogElement) { this.setAttribute("open", ""); } });
  Object.defineProperty(HTMLDialogElement.prototype, "close", { configurable: true, value: function(this: HTMLDialogElement) { this.removeAttribute("open"); } });
});
afterEach(() => vi.restoreAllMocks());
function mount(path = "/admin/leave-types", role: Identity["role"] = "ADMINISTRATOR", items = [row]) {
  window.history.replaceState({}, "", path); navigationMock.pathname = path.split("?")[0];
  sessionStorage.setItem(SESSION_KEY, JSON.stringify({ token: "test-token", expires_at: Date.now() + 60_000 }));
  server.use(http.get(`${base}/auth/me`, () => HttpResponse.json({ ...identity, role })), http.get(`${base}/leave-types`, () => HttpResponse.json({ items })));
  const client = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } });
  render(<QueryClientProvider client={client}><AuthProvider><AuthGate><LeaveTypesScreen/></AuthGate></AuthProvider></QueryClientProvider>);
  return client;
}
async function add() { await userEvent.click(await screen.findByRole("button", { name: "Add Leave Type" })); const dialog = screen.getByRole("dialog"); fireEvent.change(within(dialog).getByLabelText("Code *"), { target: { value: " new_12 " } }); fireEvent.change(within(dialog).getByLabelText("Name *"), { target: { value: " New Type " } }); return dialog; }
async function edit() { await userEvent.click(within(await screen.findByRole("table")).getByRole("button", { name: "Edit CUSTOM" })); return screen.getByRole("dialog"); }
async function toggle() { await userEvent.click(within(await screen.findByRole("table")).getByRole("button", { name: "Deactivate CUSTOM" })); return screen.getByRole("dialog"); }
async function save(dialog: HTMLElement) { await userEvent.click(within(dialog).getByRole("button", { name: "Save Leave Type" })); }

describe("Phase 12 leave types", () => {
  it.each(["EMPLOYEE", "MANAGER"] as const)("denies %s", async role => { mount("/admin/leave-types", role); expect(await screen.findByText("You don't have permission to view this page.")).toBeVisible(); expect(screen.queryByRole("table")).not.toBeInTheDocument(); });
  it("shows policy and eligibility in desktop columns and mobile cards", async () => { mount(); const table = await screen.findByRole("table", { name: "Leave types" }); expect(within(table).getByText("Allowed")).toBeVisible(); const card = screen.getByRole("article", { name: "Custom Leave (CUSTOM)" }); expect(within(card).getByText("Approval Required")).toBeVisible(); expect(within(card).getByText("Half-day Allowed")).toBeVisible(); });
  it("restores status and performs one selected-status request", async () => { mount("/admin/leave-types?status=INACTIVE"); let calls = 0; let status = ""; server.use(http.get(`${base}/leave-types`, ({ request }) => { calls++; status = new URL(request.url).searchParams.get("status")!; return HttpResponse.json({ items: [row] }); })); await screen.findByRole("table"); expect(calls).toBe(1); expect(status).toBe("INACTIVE"); expect(screen.getByLabelText("Status")).toHaveValue("INACTIVE"); await userEvent.selectOptions(screen.getByLabelText("Status"), "ACTIVE"); expect(navigationMock.replace).toHaveBeenCalledWith("/admin/leave-types?status=ACTIVE", { scroll: false }); });
  it.each(["status=BAD", "status=ACTIVE&status=ALL", "unexpected=1"])("rejects %s without reads", async query => { mount(`/admin/leave-types?${query}`); let calls = 0; server.use(http.get(`${base}/leave-types`, () => { calls++; return HttpResponse.json({ items: [row] }); })); expect(await screen.findByRole("alert")).toHaveTextContent("Invalid leave type filters"); expect(calls).toBe(0); await userEvent.click(screen.getByRole("button", { name: "Clear filters" })); expect(navigationMock.replace).toHaveBeenCalledWith("/admin/leave-types", { scroll: false }); });
  it("recovers safe list errors to empty state", async () => { mount(); server.use(http.get(`${base}/leave-types`, () => failure())); expect(await screen.findByRole("alert")).not.toHaveTextContent("private"); server.use(http.get(`${base}/leave-types`, () => HttpResponse.json({ items: [] }))); await userEvent.click(screen.getByRole("button", { name: "Retry" })); expect(await screen.findByText("No leave types match this status.")).toBeVisible(); });
  it("creates normalized fields and fixed policies, invalidating lists/previews", async () => { const client = mount(); const invalidate = vi.spyOn(client, "invalidateQueries"); let body: unknown; server.use(http.post(`${base}/admin/leave-types`, async ({ request }) => { body = await request.json(); return HttpResponse.json(row, { status: 201 }); })); const dialog = await add(); await userEvent.click(within(dialog).getByRole("switch", { name: "Paid leave" })); await userEvent.click(within(dialog).getByRole("switch", { name: "Employee application allowed" })); await save(dialog); expect(await screen.findByText("Leave type saved successfully.")).toBeVisible(); expect(body).toEqual({ code: "NEW_12", name: "New Type", description: null, is_paid: false, allow_employee_application: false, allow_half_day: false, requires_approval: true }); expect(invalidate).toHaveBeenCalledWith({ queryKey: ["leave-types"] }); expect(invalidate).toHaveBeenCalledWith({ queryKey: ["leave-preview"] }); });
  it.each([["Code *", "bad-code", "Use 1–30 letters, numbers or underscores."], ["Name *", " ", "Name is required."]])("validates %s before writes", async (label, value, error) => { mount(); let posts = 0; server.use(http.post(`${base}/admin/leave-types`, () => { posts++; return HttpResponse.json(row); })); const dialog = await add(); fireEvent.change(within(dialog).getByLabelText(label), { target: { value } }); await save(dialog); expect(await screen.findByText(error)).toBeVisible(); expect(posts).toBe(0); expect(within(dialog).getByLabelText(label)).toHaveAttribute("aria-invalid", "true"); });
  it("maps duplicate code errors to field without unsafe text", async () => { mount(); server.use(http.post(`${base}/admin/leave-types`, () => failure(409, "LEAVE_TYPE_CODE_EXISTS"))); const dialog = await add(); await save(dialog); await waitFor(() => expect(within(dialog).getByLabelText("Code *")).toHaveAttribute("aria-invalid", "true")); expect(within(dialog).getByRole("alert")).not.toHaveTextContent("private"); });
  it("prefills edit and sends full replacement without code", async () => { mount(); let body: unknown; server.use(http.put(`${base}/admin/leave-types/${id}`, async ({ request }) => { body = await request.json(); return HttpResponse.json(row); })); const dialog = await edit(); expect(within(dialog).getByLabelText("Code *")).toHaveAttribute("readonly"); expect(within(dialog).getByText("Approval required: Yes (fixed in v1)")).toBeVisible(); fireEvent.change(within(dialog).getByLabelText("Name *"), { target: { value: " Renamed " } }); await save(dialog); await screen.findByText("Leave type saved successfully."); expect(body).toEqual({ ...leaveTypeUpdate(row), name: "Renamed" }); });
  it("requires confirmation when editing to inactive", async () => { mount(); const confirm = vi.spyOn(window, "confirm").mockReturnValue(false); let puts = 0; server.use(http.put(`${base}/admin/leave-types/${id}`, () => { puts++; return HttpResponse.json(row); })); const dialog = await edit(); await userEvent.selectOptions(within(dialog).getByLabelText("Status"), "INACTIVE"); await save(dialog); expect(confirm).toHaveBeenCalledWith(expect.stringContaining("It will no longer be offered")); expect(puts).toBe(0); });
  it("preserves dirty modal on cancel/escape decline and closes on acceptance", async () => { mount(); const confirm = vi.spyOn(window, "confirm").mockReturnValue(false); const dialog = await add(); await userEvent.click(within(dialog).getByRole("button", { name: "Cancel" })); expect(dialog).toBeVisible(); fireEvent(dialog, new Event("cancel", { cancelable: true })); expect(dialog).toBeVisible(); confirm.mockReturnValue(true); await userEvent.click(within(dialog).getByRole("button", { name: "Cancel" })); expect(screen.queryByRole("dialog")).not.toBeInTheDocument(); });
  it("prevents duplicate and ambiguous resubmission", async () => { mount(); let posts = 0; let release!: () => void; const pending = new Promise<void>(resolve => { release = resolve; }); server.use(http.post(`${base}/admin/leave-types`, async () => { posts++; await pending; return failure(); })); const dialog = await add(); const button = within(dialog).getByRole("button", { name: "Save Leave Type" }); await userEvent.dblClick(button); await waitFor(() => expect(posts).toBe(1)); expect(button).toBeDisabled(); release(); expect(await screen.findByRole("alert")).toHaveTextContent("outcome is uncertain"); expect(button).toBeDisabled(); });
  it("toggles with latest fields and full payload", async () => { mount(); await screen.findByRole("table"); let body: unknown; server.use(http.get(`${base}/leave-types`, () => HttpResponse.json({ items: [{ ...row, name: "Latest", is_paid: false }] })), http.put(`${base}/admin/leave-types/${id}`, async ({ request }) => { body = await request.json(); return HttpResponse.json({ ...row, status: "INACTIVE" }); })); const dialog = await toggle(); await userEvent.click(within(dialog).getByRole("button", { name: "Deactivate" })); expect(await screen.findByText("Leave type deactivated.")).toBeVisible(); expect(body).toEqual({ ...leaveTypeUpdate(row), name: "Latest", is_paid: false, status: "INACTIVE" }); });
  it.each(["missing", "stale"])("blocks %s toggle", async mode => { mount(); await screen.findByRole("table"); let puts = 0; server.use(http.get(`${base}/leave-types`, () => HttpResponse.json({ items: mode === "missing" ? [] : [{ ...row, status: "INACTIVE" }] })), http.put(`${base}/admin/leave-types/${id}`, () => { puts++; return HttpResponse.json(row); })); const dialog = await toggle(); await userEvent.click(within(dialog).getByRole("button", { name: "Deactivate" })); expect(await screen.findByRole("alert")).toHaveTextContent(mode === "missing" ? "could not be found" : "status changed"); expect(puts).toBe(0); });
  it("activates without changing eligibility", async () => { mount("/admin/leave-types", "ADMINISTRATOR", [{ ...row, status: "INACTIVE", allow_employee_application: false }]); let body: unknown; server.use(http.put(`${base}/admin/leave-types/${id}`, async ({ request }) => { body = await request.json(); return HttpResponse.json(row); })); await userEvent.click(within(await screen.findByRole("table")).getByRole("button", { name: "Activate CUSTOM" })); await userEvent.click(within(screen.getByRole("dialog")).getByRole("button", { name: "Activate" })); await screen.findByText("Leave type activated."); expect(body).toMatchObject({ status: "ACTIVE", allow_employee_application: false }); });
  it("cycles focus and restores opener", async () => { mount(); const opener = await screen.findByRole("button", { name: "Add Leave Type" }); await userEvent.click(opener); const dialog = screen.getByRole("dialog"); const button = within(dialog).getByRole("button", { name: "Save Leave Type" }); button.focus(); await userEvent.tab(); expect(within(dialog).getByLabelText("Code *")).toHaveFocus(); await userEvent.tab({ shift: true }); expect(button).toHaveFocus(); await userEvent.click(within(dialog).getByRole("button", { name: "Cancel" })); expect(opener).toHaveFocus(); });
  it("shows loading state until the selected-status list resolves", async () => { mount(); let release!: () => void; const pending = new Promise<void>(resolve => { release = resolve; }); server.use(http.get(`${base}/leave-types`, async () => { await pending; return HttpResponse.json({ items: [row] }); })); expect(await screen.findByText("Loading your information…")).toBeVisible(); release(); expect(await screen.findByRole("table")).toBeVisible(); });
  it("rejects an oversized description before posting", async () => { mount(); let posts = 0; server.use(http.post(`${base}/admin/leave-types`, () => { posts++; return HttpResponse.json(row); })); const dialog = await add(); fireEvent.change(within(dialog).getByLabelText("Description"), { target: { value: "x".repeat(2001) } }); await save(dialog); expect(await screen.findByText("Use at most 2000 characters.")).toBeVisible(); expect(posts).toBe(0); });
  it("allows administrator-only return path", () => { expect(safeReturnTo("/admin/leave-types?status=ALL", "ADMINISTRATOR")).toBe("/admin/leave-types?status=ALL"); expect(safeReturnTo("/admin/leave-types", "MANAGER")).toBe("/dashboard"); });
});
