import { render, within, screen, waitFor, fireEvent } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { http, HttpResponse } from "msw";
import { beforeAll, afterEach, describe, it, expect, vi } from "vitest";
import { AuthProvider } from "@/features/auth/AuthProvider";
import { AuthGate } from "@/features/auth/AuthGate";
import { AdminHolidayScreen } from "@/features/holidays/AdminHolidayScreen";
import { SESSION_KEY } from "@/hooks/use-auth-session";
import { holidayUpdate } from "@/types/admin-holiday";
import { safeReturnTo } from "@/lib/permissions";
import type { Identity } from "@/types/auth";
import type { Holiday } from "@/types/employee";
import { server } from "./mocks/server";
import { navigationMock } from "./navigation-mock";
const base = "http://localhost:18000/api/v1", id = "11111111-1111-4111-8111-111111111111";
const identity: Identity = { user_id: "admin-user", employee_id: id, employee_code: "ADM001", name: "Administrator", email: "admin@example.invalid", role: "ADMINISTRATOR", department: { department_id: id, code: "ENG", name: "Engineering" }, organization_timezone: "Asia/Kolkata", business_today: "2026-10-10" };
const row: Holiday = { holiday_id: id, holiday_date: "2026-10-12", year: 2026, name: "Company Day", description: "Company holiday", is_optional: false, status: "ACTIVE" };
function failure(status = 500, code = "TRANSACTION_FAILED", details: unknown = null) { return HttpResponse.json({ error: { code, message: "private SQL password", details } }, { status }); }
beforeAll(() => {
  Object.defineProperty(HTMLDialogElement.prototype, "showModal", { configurable: true, value: function(this: HTMLDialogElement) { this.setAttribute("open", ""); } });
  Object.defineProperty(HTMLDialogElement.prototype, "close", { configurable: true, value: function(this: HTMLDialogElement) { this.removeAttribute("open"); } });
});
afterEach(() => vi.restoreAllMocks());
function mount(path = "/admin/holidays?view=list", role: Identity["role"] = "ADMINISTRATOR", items = [row]) {
  window.history.replaceState({}, "", path); navigationMock.pathname = path.split("?")[0];
  sessionStorage.setItem(SESSION_KEY, JSON.stringify({ token: "test-token", expires_at: Date.now() + 60_000 }));
  server.use(http.get(`${base}/auth/me`, () => HttpResponse.json({ ...identity, role })), http.get(`${base}/holidays`, () => HttpResponse.json({ year: 2026, items })), http.get(`${base}/holidays/${id}`, () => HttpResponse.json(items[0] ?? row)));
  const client = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } });
  render(<QueryClientProvider client={client}><AuthProvider><AuthGate><AdminHolidayScreen/></AuthGate></AuthProvider></QueryClientProvider>);
  return client;
}
async function add() { await userEvent.click(await screen.findByRole("button", { name: "Add Holiday" })); const dialog = screen.getByRole("dialog"); fireEvent.change(within(dialog).getByLabelText("Holiday name *"), { target: { value: " New Holiday " } }); fireEvent.change(within(dialog).getByLabelText("Date *"), { target: { value: "2026-10-19" } }); return dialog; }
async function edit() { await userEvent.click(within(await screen.findByRole("table")).getByRole("button", { name: "Edit Company Day" })); return screen.getByRole("dialog"); }
async function toggle(action = "Deactivate") { await userEvent.click(within(await screen.findByRole("table")).getByRole("button", { name: `${action} Company Day` })); return screen.getByRole("dialog"); }
async function save(dialog: HTMLElement) { await userEvent.click(within(dialog).getByRole("button", { name: "Save Holiday" })); }
describe("Phase 14 holiday administration", () => {
  it.each(["EMPLOYEE", "MANAGER"] as const)("denies %s", async role => { mount(undefined, role); expect(await screen.findByText("You don't have permission to view this page.")).toBeVisible(); expect(screen.queryByRole("table")).not.toBeInTheDocument(); });
  it("renders desktop columns and mobile cards with optional status", async () => { mount(); const table = await screen.findByRole("table", { name: "Managed holidays" }); expect(within(table).getByText("Mandatory")).toBeVisible(); expect(within(table).getByText("Company holiday")).toBeVisible(); expect(screen.getByRole("article", { name: "Company Day" })).toHaveTextContent("Active"); expect(screen.getByLabelText("Year")).toHaveValue("2026"); });
  it("restores year/month/inactive/view and requests the entire selected year", async () => { mount("/admin/holidays?year=2027&month=10&inactive=true&view=list"); let query = ""; server.use(http.get(`${base}/holidays`, ({ request }) => { query = new URL(request.url).search; return HttpResponse.json({ year: 2027, items: [row, { ...row, holiday_id: "other", holiday_date: "2027-11-01", name: "November" }] }); })); const table = await screen.findByRole("table"); expect(query).toContain("year=2027"); expect(query).toContain("status=ALL"); expect(query).not.toContain("month"); expect(within(table).queryByText("November")).not.toBeInTheDocument(); expect(screen.getByRole("switch", { name: "Show inactive" })).toBeChecked(); expect(screen.getByLabelText("Month")).toHaveValue("10"); });
  it.each(["year=1899", "year=2026&year=2027", "year=abc", "month=13", "month=00", "inactive=yes", "view=bad", "status=ALL"])("rejects %s without reads", async query => { mount(`/admin/holidays?${query}`); let calls = 0; server.use(http.get(`${base}/holidays`, () => { calls++; return HttpResponse.json({ items: [row] }); })); expect(await screen.findByRole("alert")).toHaveTextContent("Invalid holiday filters"); expect(calls).toBe(0); await userEvent.click(screen.getByRole("button", { name: "Clear filters" })); expect(navigationMock.replace).toHaveBeenCalledWith("/admin/holidays", { scroll: false }); });
  it("preserves rapid filter changes in the URL", async () => { mount(); await screen.findByRole("table"); await userEvent.selectOptions(screen.getByLabelText("Year"), "2027"); await userEvent.click(screen.getByRole("switch", { name: "Show inactive" })); const last = navigationMock.replace.mock.calls.at(-1)![0] as string; expect(last).toContain("year=2027"); expect(last).toContain("inactive=true"); expect(last).toContain("view=list"); });
  it("recovers a safe list error to empty state", async () => { mount(); server.use(http.get(`${base}/holidays`, () => failure())); expect(await screen.findByRole("alert")).not.toHaveTextContent("private"); server.use(http.get(`${base}/holidays`, () => HttpResponse.json({ items: [] }))); await userEvent.click(screen.getByRole("button", { name: "Retry" })); expect(await screen.findByText("No holidays match these filters.")).toBeVisible(); });
  it("marks inactive calendar holidays accessibly and opens edit", async () => { mount("/admin/holidays?view=calendar&month=10&inactive=true", "ADMINISTRATOR", [{ ...row, status: "INACTIVE" }]); await userEvent.click(await screen.findByRole("button", { name: /Company Day, Mandatory, Inactive/ })); const dialog = screen.getByRole("dialog", { name: "Edit Holiday" }); expect(within(dialog).getByLabelText("Status")).toHaveValue("INACTIVE"); expect(within(dialog).getByLabelText("Date *")).toHaveValue(row.holiday_date); });
  it("creates normalized date/name/optional fields and invalidates affected caches", async () => { const client = mount(); const invalidate = vi.spyOn(client, "invalidateQueries"); let body: unknown; server.use(http.post(`${base}/admin/holidays`, async ({ request }) => { body = await request.json(); return HttpResponse.json(row, { status: 201 }); })); const dialog = await add(); await userEvent.click(within(dialog).getByRole("switch", { name: "Optional holiday" })); await save(dialog); expect(await screen.findByText("Holiday saved. Changes apply to future leave-day calculations.")).toBeVisible(); expect(body).toEqual({ name: "New Holiday", holiday_date: "2026-10-19", description: null, is_optional: true }); for (const key of ["holidays", "dashboard", "leave-preview"]) expect(invalidate).toHaveBeenCalledWith({ queryKey: [key] }); });
  it.each([["Holiday name *", " ", "Holiday name is required."], ["Holiday name *", "x".repeat(201), "Use at most 200 characters."], ["Date *", "", "Choose a valid calendar date."], ["Description", "x".repeat(2001), "Use at most 2000 characters."]])("validates %s before writes", async (label, value, message) => { mount(); let posts = 0; server.use(http.post(`${base}/admin/holidays`, () => { posts++; return HttpResponse.json(row); })); const dialog = await add(); fireEvent.change(within(dialog).getByLabelText(label), { target: { value } }); await save(dialog); expect(await screen.findByText(message)).toBeVisible(); expect(posts).toBe(0); expect(within(dialog).getByLabelText(label)).toHaveAttribute("aria-invalid", "true"); });
  it("maps duplicate date to the date field without unsafe server text", async () => { mount(); server.use(http.post(`${base}/admin/holidays`, () => failure(409, "HOLIDAY_DATE_EXISTS"))); const dialog = await add(); await save(dialog); await waitFor(() => expect(within(dialog).getByLabelText("Date *")).toHaveAttribute("aria-invalid", "true")); expect(within(dialog).getByRole("alert")).not.toHaveTextContent("private"); });
  it("maps validation details to the date field", async () => { mount(); server.use(http.post(`${base}/admin/holidays`, () => failure(422, "VALIDATION_ERROR", [{ field: "body.holiday_date", message: "private" }]))); const dialog = await add(); await save(dialog); expect(await screen.findByText("Check this value.")).toBeVisible(); expect(within(dialog).getByLabelText("Date *")).toHaveAttribute("aria-invalid", "true"); });
  it("edits full replacement and redirects to the derived year", async () => { mount("/admin/holidays?view=list&month=10"); let body: unknown; server.use(http.put(`${base}/admin/holidays/${id}`, async ({ request }) => { body = await request.json(); return HttpResponse.json({ ...row, holiday_date: "2027-01-01", year: 2027 }); })); const dialog = await edit(); fireEvent.change(within(dialog).getByLabelText("Date *"), { target: { value: "2027-01-01" } }); await save(dialog); await screen.findByText("Holiday saved. Changes apply to future leave-day calculations."); expect(body).toEqual({ ...holidayUpdate(row), holiday_date: "2027-01-01" }); const url = navigationMock.replace.mock.calls.at(-1)![0] as string; expect(url).toContain("year=2027"); expect(url).not.toContain("month"); });
  it("requires confirmation when editing status", async () => { mount(); const confirm = vi.spyOn(window, "confirm").mockReturnValue(false); let writes = 0; server.use(http.put(`${base}/admin/holidays/${id}`, () => { writes++; return HttpResponse.json(row); })); const dialog = await edit(); await userEvent.selectOptions(within(dialog).getByLabelText("Status"), "INACTIVE"); await save(dialog); expect(confirm).toHaveBeenCalledWith(expect.stringContaining("future leave-day calculations")); expect(writes).toBe(0); });
  it("deactivates using DELETE after a fresh read", async () => { mount(); let writes = 0; let body = ""; server.use(http.delete(`${base}/admin/holidays/${id}`, async ({ request }) => { writes++; body = await request.text(); return HttpResponse.json({ ...row, status: "INACTIVE" }); })); const dialog = await toggle(); await userEvent.click(within(dialog).getByRole("button", { name: "Deactivate" })); await screen.findByText("Holiday deactivated. Changes apply to future leave-day calculations."); expect(writes).toBe(1); expect(body).toBe(""); });
  it("activates with latest full fields", async () => { mount(undefined, "ADMINISTRATOR", [{ ...row, status: "INACTIVE" }]); let body: unknown; server.use(http.get(`${base}/holidays/${id}`, () => HttpResponse.json({ ...row, status: "INACTIVE", description: "Latest", is_optional: true })), http.put(`${base}/admin/holidays/${id}`, async ({ request }) => { body = await request.json(); return HttpResponse.json(row); })); const dialog = await toggle("Activate"); await userEvent.click(within(dialog).getByRole("button", { name: "Activate" })); await screen.findByText("Holiday activated. Changes apply to future leave-day calculations."); expect(body).toEqual({ ...holidayUpdate(row), description: "Latest", is_optional: true }); });
  it.each(["missing", "stale"])("blocks %s toggle without writing", async mode => { mount(); let writes = 0; server.use(http.get(`${base}/holidays/${id}`, () => mode === "missing" ? failure(404, "HOLIDAY_NOT_FOUND") : HttpResponse.json({ ...row, status: "INACTIVE" })), http.delete(`${base}/admin/holidays/${id}`, () => { writes++; return HttpResponse.json(row); })); const dialog = await toggle(); await userEvent.click(within(dialog).getByRole("button", { name: "Deactivate" })); expect(await screen.findByRole("alert")).toHaveTextContent(mode === "missing" ? "could not be found" : "status changed"); expect(writes).toBe(0); });
  it.each(["server", "network", "malformed"])("blocks blind resubmission after %s result", async mode => { mount(); let posts = 0; server.use(http.post(`${base}/admin/holidays`, () => { posts++; return mode === "server" ? failure() : mode === "network" ? HttpResponse.error() : HttpResponse.json({}); })); const dialog = await add(); await save(dialog); expect(await screen.findByText(/outcome is uncertain/)).toBeVisible(); expect(within(dialog).getByRole("button", { name: "Save Holiday" })).toBeDisabled(); expect(posts).toBe(1); });
  it("prevents duplicate writes and closing while pending", async () => { mount(); let posts = 0; let release!: () => void; const pending = new Promise<void>(resolve => { release = resolve; }); server.use(http.post(`${base}/admin/holidays`, async () => { posts++; await pending; return HttpResponse.json(row); })); const dialog = await add(); await userEvent.dblClick(within(dialog).getByRole("button", { name: "Save Holiday" })); await waitFor(() => expect(posts).toBe(1)); expect(within(dialog).getByRole("button", { name: "Cancel" })).toBeDisabled(); fireEvent(dialog, new Event("cancel", { cancelable: true })); expect(dialog).toBeVisible(); release(); await screen.findByText("Holiday saved. Changes apply to future leave-day calculations."); });
  it("keeps dirty forms on declined cancel and escape", async () => { mount(); const confirm = vi.spyOn(window, "confirm").mockReturnValue(false); const dialog = await add(); await userEvent.click(within(dialog).getByRole("button", { name: "Cancel" })); fireEvent(dialog, new Event("cancel", { cancelable: true })); expect(dialog).toBeVisible(); confirm.mockReturnValue(true); await userEvent.click(within(dialog).getByRole("button", { name: "Cancel" })); expect(screen.queryByRole("dialog")).not.toBeInTheDocument(); });
  it("cycles focus and restores opener", async () => { mount(); const opener = await screen.findByRole("button", { name: "Add Holiday" }); await userEvent.click(opener); const dialog = screen.getByRole("dialog"), button = within(dialog).getByRole("button", { name: "Save Holiday" }); button.focus(); await userEvent.tab(); expect(within(dialog).getByLabelText("Holiday name *")).toHaveFocus(); await userEvent.tab({ shift: true }); expect(button).toHaveFocus(); await userEvent.click(within(dialog).getByRole("button", { name: "Cancel" })); expect(opener).toHaveFocus(); });
  it.each([false, true])("defaults to responsive view with mobile=%s", async mobile => { vi.stubGlobal("matchMedia", vi.fn(() => ({ matches: mobile, addEventListener: vi.fn(), removeEventListener: vi.fn() }))); try { mount("/admin/holidays"); expect(await screen.findByRole("button", { name: mobile ? "List" : "Calendar" })).toHaveAttribute("aria-pressed", "true"); if (mobile) await screen.findByRole("article"); else await screen.findByRole("region", { name: "Holiday calendar" }); } finally { vi.unstubAllGlobals(); } });
  it("shows loading until the selected-year read resolves", async () => { mount(); let release!: () => void; const pending = new Promise<void>(resolve => { release = resolve; }); server.use(http.get(`${base}/holidays`, async () => { await pending; return HttpResponse.json({ items: [row] }); })); expect(await screen.findByText("Loading your information…")).toBeVisible(); release(); expect(await screen.findByRole("table")).toBeVisible(); });
  it("invalidates affected caches even on an unsuccessful write", async () => { const client = mount(); const invalidate = vi.spyOn(client, "invalidateQueries"); server.use(http.post(`${base}/admin/holidays`, () => failure(409, "HOLIDAY_DATE_EXISTS"))); const dialog = await add(); await save(dialog); await waitFor(() => expect(within(dialog).getByLabelText("Date *")).toHaveAttribute("aria-invalid", "true")); for (const key of ["holidays", "dashboard", "leave-preview"]) expect(invalidate).toHaveBeenCalledWith({ queryKey: [key] }); });
  it("allows only administrators to return to holiday administration", () => { expect(safeReturnTo("/admin/holidays?year=2026", "ADMINISTRATOR")).toBe("/admin/holidays?year=2026"); expect(safeReturnTo("/admin/holidays", "EMPLOYEE")).toBe("/dashboard"); });
});
