import { render, screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { http, HttpResponse } from "msw";
import { beforeAll, describe, it, expect, vi } from "vitest";
import { AuthProvider } from "@/features/auth/AuthProvider";
import { AuthGate } from "@/features/auth/AuthGate";
import { LeaveHistoryScreen } from "@/features/leave/LeaveHistoryScreen";
import { ApplicationDetailScreen } from "@/features/leave/ApplicationDetailScreen";
import { SESSION_KEY } from "@/hooks/use-auth-session";
import { leaveService } from "@/services/leave-service";
import type { Identity } from "@/types/auth";
import type { Application } from "@/types/leave";
import type { ApplicationRow } from "@/types/employee";
import { server } from "./mocks/server";
import { navigationMock } from "./navigation-mock";
const origin="http://localhost:18000/api/v1", id="11111111-1111-4111-8111-111111111111", typeId="22222222-2222-4222-8222-222222222222";
const user: Identity={user_id:"u1",employee_id:"e1",employee_code:"EMP001",name:"Employee",email:"emp@example.invalid",role:"EMPLOYEE",department:{department_id:"d1",code:"ENG",name:"Engineering"},organization_timezone:"Asia/Kolkata",business_today:"2026-10-09"};
const application: Application={application_id:id,employee:{employee_id:"e1",employee_code:"EMP001",name:"Employee"},leave_type:{leave_type_id:typeId,code:"EARNED",name:"Earned Leave"},from_date:"2026-10-12",to_date:"2026-10-13",number_of_days:2,reason:"Personal",status:"PENDING",manager:{employee_id:"m1",employee_code:"MGR001",name:"Manager"},approved_by:null,rejected_by:null,cancelled_by:null,approved_at:null,rejected_at:null,cancelled_at:null,approval_comment:null,rejection_reason:null,cancellation_reason:null,created_at:"2026-10-09T00:00:00Z",updated_at:null};
const statuses: Application["status"][]=["PENDING","APPROVED","REJECTED","CANCELLED"];
const rows: ApplicationRow[]=statuses.map((status,index)=>({application_id:index ? `${index}1111111-1111-4111-8111-111111111111` : id,employee_id:"e1",employee_code:"EMP001",employee_name:"Employee",department:user.department,manager:application.manager,leave_type_id:typeId,leave_type:"EARNED",leave_type_name:"Earned Leave",from_date:application.from_date,to_date:application.to_date,number_of_days:2,reason:"Personal",status,created_at:application.created_at}));
beforeAll(()=>{
  // jsdom lacks native modal behavior; Chromium checks real focus and Escape.
  Object.defineProperty(HTMLDialogElement.prototype,"showModal",{configurable:true,value:function(this: HTMLDialogElement){this.setAttribute("open","");}});
  Object.defineProperty(HTMLDialogElement.prototype,"close",{configurable:true,value:function(this: HTMLDialogElement){this.removeAttribute("open");}});
});
function mount(search="",detail=false,identity=user,item=application){
  const path=detail ? `/leave/applications/${id}` : "/leave/history";navigationMock.pathname=path;window.history.replaceState({},"",path+search);
  sessionStorage.setItem(SESSION_KEY,JSON.stringify({token:"test-token",expires_at:Date.now()+60_000}));
  server.use(http.get(`${origin}/auth/me`,()=>HttpResponse.json(identity)),http.get(`${origin}/leave-types`,()=>HttpResponse.json({items:[{leave_type_id:typeId,name:"Earned Leave",status:"ACTIVE",allow_employee_application:true}]})),http.get(`${origin}/leave/applications/${id}`,()=>HttpResponse.json(item)));
  const client=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}});
  return {client,...render(<QueryClientProvider client={client}><AuthProvider><AuthGate>{detail ? <ApplicationDetailScreen id={id}/> : <LeaveHistoryScreen/>}</AuthGate></AuthProvider></QueryClientProvider>)};
}
function history(items=rows,total=items.length){server.use(http.get(`${origin}/employees/e1/leave-applications`,({request})=>{const p=new URL(request.url).searchParams;return HttpResponse.json({employee_id:"e1",employee_code:"EMP001",items,total,page:Number(p.get("page")??1),page_size:Number(p.get("page_size")??20)});}));}
const cancelButton=()=>within(screen.getByRole("table")).getByRole("button",{name:"Cancel"});
describe("Phase 7 History",()=>{
  it("loads own year history, badges, detail links and only pending cancellation",async()=>{history();mount();await screen.findByRole("table");expect(screen.getByLabelText("Year")).toHaveValue("2026");expect(within(screen.getByRole("table")).getAllByRole("button",{name:"Cancel"})).toHaveLength(1);for(const status of statuses) expect(within(screen.getByRole("table")).getByText(status,{exact:true})).toBeVisible();expect(within(screen.getByRole("table")).getAllByRole("link",{name:"View"})).toHaveLength(4);expect(screen.getByRole("button",{name:"Next"})).toBeDisabled();});
  it("syncs filters to URL, resets page and preserves other filters",async()=>{history();mount("?year=2026&status=PENDING&page=3&page_size=1");await screen.findByRole("table");await userEvent.selectOptions(screen.getByLabelText("Status"),"APPROVED");expect(navigationMock.replace).toHaveBeenCalledWith("/leave/history?year=2026&status=APPROVED&page_size=1",{scroll:false});await userEvent.click(screen.getByRole("button",{name:"Previous"}));expect(navigationMock.replace).toHaveBeenCalledWith("/leave/history?year=2026&status=APPROVED&page_size=1&page=2",{scroll:false});await userEvent.click(screen.getByRole("button",{name:"Clear filters"}));expect(navigationMock.replace).toHaveBeenCalledWith("/leave/history",{scroll:false});await userEvent.selectOptions(screen.getByLabelText("Per page"),"50");expect(navigationMock.replace).toHaveBeenCalledWith("/leave/history?page_size=50",{scroll:false});});
  it("preserves rapid date edits before the router updates the URL",async()=>{
    history();mount();await screen.findByRole("table");
    await userEvent.type(screen.getByLabelText("Leave From"),"2026-10-12");
    await userEvent.type(screen.getByLabelText("Leave To"),"2026-10-13");
    expect(navigationMock.replace).toHaveBeenLastCalledWith("/leave/history?from_date=2026-10-12&to_date=2026-10-13",{scroll:false});
  });
  it("uses explicit own scope on general endpoint for date filters",async()=>{let seen="";server.use(http.get(`${origin}/leave/applications`,({request})=>{seen=request.url;return HttpResponse.json({items:rows,total:4,page:1,page_size:20});}));mount(`?year=2026&from_date=2026-10-12&to_date=2026-10-13&leave_type_id=${typeId}`);await screen.findByRole("table");const p=new URL(seen).searchParams;expect(p.get("scope")).toBe("own");expect(p.get("employee_id")).toBe("e1");expect(p.get("from_date")).toBe("2026-10-12");expect(p.get("leave_type_id")).toBe(typeId);});
  it.each(["?page=0","?year=2026&year=2027","?from_date=2026-02-30","?from_date=2026-10-13&to_date=2026-10-12","?extra=x"])("rejects malformed URL %s without a history request",async search=>{const spy=vi.spyOn(leaveService,"history");mount(search);expect(await screen.findByRole("alert")).toHaveTextContent("Invalid history filters");expect(spy).not.toHaveBeenCalled();spy.mockRestore();});
  it("shows loading then empty and Apply Leave",async()=>{let release!:()=>void;const pending=new Promise<void>(resolve=>{release=resolve;});server.use(http.get(`${origin}/employees/e1/leave-applications`,async()=>{await pending;return HttpResponse.json({items:[],total:0,page:1,page_size:20});}));mount();expect(await screen.findByText("Loading your information…")).toBeVisible();release();expect(await screen.findByText("You haven't applied for leave yet.")).toBeVisible();expect(screen.getByRole("link",{name:"Apply Leave"})).toHaveAttribute("href","/leave/apply");});
  it.each([403,500])("shows safe %s history errors",async status=>{server.use(http.get(`${origin}/employees/e1/leave-applications`,()=>HttpResponse.json({error:{code:status===403 ? "FORBIDDEN" : "SERVER_ERROR",message:"private SQL"}},{status})));mount();expect(await screen.findByText(status===403 ? "Access restricted" : "Something went wrong. Please try again later.")).toBeVisible();expect(screen.queryByText("private SQL")).not.toBeInTheDocument();});
  it("preserves selected historical type and out-of-range page controls",async()=>{history([],3);mount("?page=5&page_size=1&leave_type_id=33333333-3333-4333-8333-333333333333");expect(await screen.findByText("No applications on this page.")).toBeVisible();expect(screen.getByLabelText("Leave Type")).toHaveValue("33333333-3333-4333-8333-333333333333");expect(screen.getByRole("button",{name:"Previous"})).toBeEnabled();expect(screen.getByRole("button",{name:"Next"})).toBeDisabled();});
});
describe("Phase 7 cancellation",()=>{
  it("Keep and Escape close the dialog without a request",async()=>{history();mount();await screen.findByRole("table");await userEvent.click(cancelButton());const dialog=screen.getByRole("dialog");expect(dialog).toHaveAccessibleName("Cancel this leave application?");const spy=vi.spyOn(leaveService,"cancel");await userEvent.click(within(dialog).getByRole("button",{name:"Keep application"}));expect(screen.queryByRole("dialog")).not.toBeInTheDocument();expect(spy).not.toHaveBeenCalled();await userEvent.click(cancelButton());screen.getByRole("dialog").dispatchEvent(new Event("cancel",{cancelable:true,bubbles:true}));await waitFor(()=>expect(screen.queryByRole("dialog")).not.toBeInTheDocument());spy.mockRestore();});
  it("cycles Tab and Shift+Tab within the dialog",async()=>{
    history();mount();await screen.findByRole("table");await userEvent.click(cancelButton());
    const dialog=screen.getByRole("dialog");const first=within(dialog).getByLabelText("Cancellation reason (optional)");const last=within(dialog).getByRole("button",{name:"Cancel application"});
    first.focus();await userEvent.tab({shift:true});expect(last).toHaveFocus();await userEvent.tab();expect(first).toHaveFocus();
  });
  it("trims reason, prevents double clicks and refreshes after success",async()=>{let status: Application["status"]="PENDING",calls=0;let release!:()=>void;const pending=new Promise<void>(resolve=>{release=resolve;});server.use(http.get(`${origin}/employees/e1/leave-applications`,()=>HttpResponse.json({items:[{...rows[0],status}],total:1,page:1,page_size:20})),http.post(`${origin}/leave/applications/${id}/cancel`,async({request})=>{calls++;expect(await request.json()).toEqual({reason:"Changed plans"});await pending;status="CANCELLED";return HttpResponse.json({...application,status,cancellation_reason:"Changed plans",cancelled_by:application.employee,cancelled_at:"2026-10-09T00:00:00Z"});}));const {client}=mount();const invalidate=vi.spyOn(client,"invalidateQueries");await screen.findByRole("table");await userEvent.click(cancelButton());await userEvent.type(screen.getByLabelText("Cancellation reason (optional)")," Changed plans ");await userEvent.dblClick(screen.getByRole("button",{name:"Cancel application"}));expect(screen.getByRole("button",{name:"Cancelling…"})).toBeDisabled();expect(screen.getByRole("button",{name:"Keep application"})).toBeDisabled();expect(calls).toBe(1);release();await waitFor(()=>expect(screen.queryByRole("dialog")).not.toBeInTheDocument());expect(screen.getByRole("status")).toHaveTextContent("Leave application cancelled");expect(within(screen.getByRole("table")).getByText("CANCELLED")).toBeVisible();expect(within(screen.getByRole("table")).queryByRole("button",{name:"Cancel"})).not.toBeInTheDocument();for(const key of ["balances","applications","dashboard","approvals","notifications"]) expect(invalidate).toHaveBeenCalledWith({queryKey:[key]});});
  it("submits blank optional reason as an empty object",async()=>{history();let body: unknown;server.use(http.post(`${origin}/leave/applications/${id}/cancel`,async({request})=>{body=await request.json();return HttpResponse.json({...application,status:"CANCELLED"});}));mount();await screen.findByRole("table");await userEvent.click(cancelButton());await userEvent.type(screen.getByLabelText("Cancellation reason (optional)"),"   ");await userEvent.click(screen.getByRole("button",{name:"Cancel application"}));await waitFor(()=>expect(body).toEqual({}));});
  it("refetches conflicts, preserves reason and disables terminal submission",async()=>{history();server.use(http.post(`${origin}/leave/applications/${id}/cancel`,()=>HttpResponse.json({error:{code:"INVALID_LEAVE_STATUS",message:"unsafe"}},{status:409})));const {client}=mount();const invalidate=vi.spyOn(client,"invalidateQueries");await screen.findByRole("table");await userEvent.click(cancelButton());await userEvent.type(screen.getByLabelText("Cancellation reason (optional)"),"Keep my text");await userEvent.click(screen.getByRole("button",{name:"Cancel application"}));expect(await screen.findByRole("alert")).toHaveTextContent("already been processed");expect(screen.getByLabelText("Cancellation reason (optional)")).toHaveValue("Keep my text");expect(screen.getByRole("button",{name:"Cancel application"})).toBeDisabled();expect(invalidate).toHaveBeenCalledWith({queryKey:["applications"]});});
  it.each(["network","server","malformed"])("does not replay ambiguous %s failure",async mode=>{history();let calls=0;server.use(http.post(`${origin}/leave/applications/${id}/cancel`,()=>{calls++;return mode==="network" ? HttpResponse.error() : mode==="server" ? HttpResponse.json({error:{code:"TRANSACTION_FAILED"}},{status:500}) : new HttpResponse("{bad json",{headers:{"Content-Type":"application/json"}});}));mount();await screen.findByRole("table");await userEvent.click(cancelButton());await userEvent.click(screen.getByRole("button",{name:"Cancel application"}));expect(await screen.findByRole("alert")).toHaveTextContent("outcome is uncertain");expect(screen.getByRole("button",{name:"Cancel application"})).toBeDisabled();expect(calls).toBe(1);});
  it.each(["EMPLOYEE","MANAGER","ADMINISTRATOR"] as const)("allows %s owner detail cancellation",async role=>{mount("",true,{...user,role});expect(await screen.findByRole("button",{name:"Cancel"})).toBeVisible();expect(screen.queryByRole("button",{name:"Approve"})).not.toBeInTheDocument();});
  it.each(["APPROVED","REJECTED","CANCELLED"] as const)("hides Cancel for %s",async status=>{mount("",true,user,{...application,status});await screen.findByText(status,{exact:true});expect(screen.queryByRole("button",{name:"Cancel"})).not.toBeInTheDocument();});
  it("hides Cancel for a non-owner manager",async()=>{mount("",true,{...user,employee_id:"m1",role:"MANAGER"});await screen.findByText("PENDING",{exact:true});expect(screen.queryByRole("button",{name:"Cancel"})).not.toBeInTheDocument();});
});
