import { render, screen, within, fireEvent, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { http, HttpResponse } from "msw";
import { describe, expect, it } from "vitest";
import type { ReactNode } from "react";
import { AuthProvider } from "@/features/auth/AuthProvider";
import { AuthGate } from "@/features/auth/AuthGate";
import { ReportsScreen } from "@/features/reports/ReportsScreen";
import { UtilizationCell } from "@/features/reports/UtilizationCell";
import { SESSION_KEY } from "@/hooks/use-auth-session";
import { utilizationPercent } from "@/lib/format";
import { safeReturnTo } from "@/lib/permissions";
import { reportService } from "@/services/report-service";
import { reportTabs } from "@/types/report";
import type { Identity } from "@/types/auth";
import type { BalanceRow } from "@/types/admin-balance";
import type { ApplicationRow, Holiday } from "@/types/employee";
import { navigationMock } from "./navigation-mock";
import { server } from "./mocks/server";
const origin = "http://localhost:18000/api/v1", employeeId = "22222222-2222-4222-8222-222222222222", typeId = "33333333-3333-4333-8333-333333333333";
const identity: Identity = { user_id: "report-user", employee_id: employeeId, employee_code: "EMP001", name: "Report Subject", email: "subject@example.invalid", role: "EMPLOYEE", department: { department_id: "44444444-4444-4444-8444-444444444444", code: "ENG", name: "Engineering" }, organization_timezone: "Asia/Kolkata", business_today: "2026-10-10" };
const balance: BalanceRow = { balance_id: "55555555-5555-4555-8555-555555555555", employee_id: employeeId, leave_type_id: typeId, leave_year: 2026, employee: { employee_id: employeeId, employee_code: "EMP001", name: identity.name }, department: identity.department, leave_type: { leave_type_id: typeId, code: "HISTORICAL", name: "Historical Leave" }, allocated: 20, carried_forward: 5, used: 5, pending: 2, available: 18 };
const application: ApplicationRow = { application_id: "66666666-6666-4666-8666-666666666666", employee_id: employeeId, employee_code: "EMP001", employee_name: identity.name, department: identity.department, manager: { employee_id: "11111111-1111-4111-8111-111111111111", employee_code: "MGR001", name: "Report Manager" }, leave_type_id: typeId, leave_type: "HISTORICAL", leave_type_name: "Historical Leave", from_date: "2026-10-09", to_date: "2026-10-12", number_of_days: 2, reason: "Private", status: "APPROVED", created_at: "2026-10-01T00:00:00Z" };
const holiday: Holiday = { holiday_id: "holiday", holiday_date: "2026-10-10", name: "<script>Holiday</script>", description: null, year: 2026, is_optional: false, status: "INACTIVE" };
function url(search = "") { window.history.replaceState({}, "", `/reports${search}`); navigationMock.pathname = "/reports"; }
function defaults(rows = [balance], apps = [application], holidays = [holiday]) {
  server.use(
    http.get(`${origin}/reports/leave-summary`, ({ request }) => { const p = new URL(request.url).searchParams; return HttpResponse.json({ year: Number(p.get("year")), items: rows, total: rows.length, page: Number(p.get("page")), page_size: Number(p.get("page_size")) }); }),
    http.get(`${origin}/leave/applications`, ({ request }) => { const p = new URL(request.url).searchParams; return HttpResponse.json({ items: apps, total: p.get("page_size") === "1" ? ({ PENDING: 7, APPROVED: 8, REJECTED: 3 }[p.get("status")!] ?? 0) : apps.length, page: Number(p.get("page")), page_size: Number(p.get("page_size")) }); }),
    http.get(`${origin}/holidays`, () => HttpResponse.json({ year: 2026, month: null, items: holidays })),
    http.get(`${origin}/leave-types`, () => HttpResponse.json({ items: [] })),
    http.get(`${origin}/managers/me/direct-reports`, () => HttpResponse.json({ items: [], total: 0, page: 1, page_size: 20 })),
    http.get(`${origin}/employees`, () => HttpResponse.json({ items: [], total: 0, page: 1, page_size: 20 })),
    http.get(`${origin}/departments`, () => HttpResponse.json({ items: [identity.department] })),
  );
}
function mount(role: Identity["role"] = "EMPLOYEE") {
  sessionStorage.setItem(SESSION_KEY, JSON.stringify({ token: "test-token", expires_at: Date.now() + 60_000 }));
  server.use(http.get(`${origin}/auth/me`, () => HttpResponse.json({ ...identity, role })));
  const client = new QueryClient({ defaultOptions: { queries: { retry: false } } });
  const wrapper = ({ children }: { children: ReactNode }) => <QueryClientProvider client={client}><AuthProvider><AuthGate>{children}</AuthGate></AuthProvider></QueryClientProvider>;
  return { ...render(<ReportsScreen/>, { wrapper }), client };
}
describe("utilization presentation", () => {
  it.each([[5, 20, 25], [1, 3, 33.3], [0, 20, 0], [12, 10, 120], [0.25, 10, 2.5]])("rounds %s / %s", (used, allocated, expected) => expect(utilizationPercent(used, allocated)).toBe(expected));
  it.each([[1, 0], [0, 0], [1, undefined], [undefined, 20], [null, 20], [1, null], [Infinity, 20], [1, Infinity], [NaN, 20], [-1, 20], [1, -20], [Number.MAX_VALUE, 1]])("guards invalid numbers %s / %s", (used, allocated) => expect(utilizationPercent(used, allocated)).toBeNull());
  it("shows em dash and a bounded visual bar with uncapped text", () => { const result = render(<UtilizationCell used={1} allocated={0}/>); expect(screen.getByLabelText("Utilization unavailable")).toHaveTextContent("—"); result.rerender(<UtilizationCell used={12} allocated={10}/>); expect(screen.getByText("120.0%")).toBeVisible(); expect(result.container.querySelector('[style="width: 100%;"]')).not.toBeNull(); expect(result.container).not.toHaveTextContent(/NaN|Infinity/); });
});
describe("report services", () => {
  it("sends only summary contract fields", async () => { let query = new URLSearchParams(); server.use(http.get(`${origin}/reports/leave-summary`, ({ request }) => { query = new URL(request.url).searchParams; return HttpResponse.json({ year: 2026, items: [], total: 0, page: 1, page_size: 20 }); })); await reportService.summary({ year: 2026, page: 1, page_size: 20, employee_id: employeeId, department_id: identity.department.department_id, leave_type_id: typeId, status: "PENDING", from_date: "2026-10-01" }, "team"); expect(query.get("scope")).toBe("team"); expect(query.get("employee_id")).toBe(employeeId); expect(query.has("status")).toBe(false); expect(query.has("from_date")).toBe(false); });
  it("uses API totals for independent statuses and ignores list status/page", async () => { const calls: URLSearchParams[] = []; server.use(http.get(`${origin}/leave/applications`, ({ request }) => { const p = new URL(request.url).searchParams; calls.push(p); return HttpResponse.json({ items: [], total: p.get("status") === "PENDING" ? 7 : 2, page: 1, page_size: 1 }); })); expect(await reportService.counts({ year: 2026, page: 5, page_size: 20, status: "CANCELLED", employee_id: employeeId }, "organization")).toEqual([{ status: "PENDING", total: 7 }, { status: "APPROVED", total: 2 }, { status: "REJECTED", total: 2 }]); expect(calls).toHaveLength(3); expect(calls.every(p => p.get("page") === "1" && p.get("page_size") === "1" && p.get("scope") === "organization" && p.get("employee_id") === employeeId)).toBe(true); });
  it("forwards abort signal", async () => { const controller = new AbortController(); controller.abort(); await expect(reportService.summary({ year: 2026, page: 1, page_size: 20 }, "own", controller.signal)).rejects.toMatchObject({ name: "AbortError" }); });
});
describe("role reports", () => {
  it.each(["EMPLOYEE", "MANAGER", "ADMINISTRATOR"] as const)("loads %s summary with correct scope, tabs and no exports", async role => { defaults(); url(); let scope = ""; server.use(http.get(`${origin}/reports/leave-summary`, ({ request }) => { scope = new URL(request.url).searchParams.get("scope")!; return HttpResponse.json({ year: 2026, items: [balance], total: 1, page: 1, page_size: 20 }); })); mount(role); const table = await screen.findByRole("table", { name: "Leave summary report" }); expect(screen.getByText("Scroll horizontally to view all summary columns.")).toBeVisible(); expect(scope).toBe(role === "EMPLOYEE" ? "own" : role === "MANAGER" ? "team" : "organization"); expect(within(table).getByText(identity.name)).toBeVisible(); const nav = screen.getByRole("navigation", { name: "Report views" }); expect(within(nav).getAllByRole("button")).toHaveLength(reportTabs(role).length); expect(screen.queryByRole("button", { name: /export|csv|excel|pdf/i })).toBeNull(); expect(safeReturnTo("/reports", role)).toBe("/reports"); if (role === "MANAGER") expect(within(nav).getByRole("link", { name: "Pending Approvals" })).toHaveAttribute("href", "/approvals"); if (role !== "ADMINISTRATOR") expect(within(table).getByText("25.0%")).toBeVisible(); });
  it("shows administrator utilization including historical zero-allocation rows", async () => { defaults([{ ...balance, allocated: 0, used: 1 }]); url("?tab=utilization"); mount("ADMINISTRATOR"); const table = await screen.findByRole("table"); expect(within(table).getByLabelText("Utilization unavailable")).toHaveTextContent("—"); expect(screen.getByRole("option", { name: "Historical Leave" })).toBeVisible(); });
  it.each(["EMPLOYEE", "MANAGER"] as const)("renders %s application history in read-only desktop and mobile rows", async role => { defaults(); url("?tab=applications"); mount(role); const table = await screen.findByRole("table", { name: "Leave application report" }); expect(screen.getByText("Scroll horizontally to view all application columns.")).toBeVisible(); expect(within(table).getByText("Report Manager (MGR001)")).toBeVisible(); expect(within(table).getByRole("link", { name: `View application ${application.application_id}` })).toHaveAttribute("href", `/leave/applications/${application.application_id}`); expect(within(table).getByText("2")).toBeVisible(); expect(screen.queryByRole("button", { name: /^(Approve|Reject|Cancel|Export)$/ })).toBeNull(); expect(screen.getByRole("article")).toHaveTextContent("Report Manager (MGR001)"); if (role === "EMPLOYEE") expect(screen.getByRole("link", { name: "Open My Leave History" })).toHaveAttribute("href", "/leave/history"); });
  it("renders admin status totals and application list independently", async () => { defaults(); url("?tab=applications&status=CANCELLED&page=2"); mount("ADMINISTRATOR"); await screen.findByRole("table"); const counts = screen.getByRole("region", { name: "Application status summary" }); expect(await within(counts).findByText("7")).toBeVisible(); expect(within(counts).getByText("8")).toBeVisible(); expect(within(counts).getByText("3")).toBeVisible(); expect(screen.getByLabelText("Status")).toHaveValue("CANCELLED"); });
  it("renders all-status holiday report with text-safe names", async () => { defaults(); url("?tab=holidays&year=2026"); let params = new URLSearchParams(); server.use(http.get(`${origin}/holidays`, ({ request }) => { params = new URL(request.url).searchParams; return HttpResponse.json({ items: [holiday] }); })); mount("ADMINISTRATOR"); const table = await screen.findByRole("table", { name: "Holiday report" }); expect(screen.getByText("Scroll horizontally to view all holiday columns.")).toBeVisible(); expect(within(table).getByText(holiday.name)).toBeVisible(); expect(within(table).getByText("INACTIVE")).toBeVisible(); expect(params.get("status")).toBe("ALL"); expect(params.get("year")).toBe("2026"); expect(table.querySelector("script")).toBeNull(); expect(screen.queryByRole("navigation", { name: /pagination/ })).toBeNull(); });
  it.each(["?scope=organization", "?tab=holidays", "?tab=utilization", "?year=1899", "?page=0", "?page_size=101", "?year=2026&year=2027", "?employee_id=invalid", "?department_id=bad", "?tab=applications&status=UNKNOWN", "?tab=applications&from_date=2026-02-30", "?tab=applications&from_date=2026-10-20&to_date=2026-10-01"])("rejects invalid employee URL %s without reports API requests", async search => { defaults(); url(search); let called = false; server.use(http.get(`${origin}/reports/leave-summary`, () => { called = true; return HttpResponse.json({}); }), http.get(`${origin}/leave/applications`, () => { called = true; return HttpResponse.json({}); })); mount(); expect(await screen.findByRole("alert")).toHaveTextContent("Invalid report filters"); expect(called).toBe(false); await userEvent.click(screen.getByRole("button", { name: "Clear filters" })); expect(navigationMock.replace).toHaveBeenCalled(); });
  it("merges rapid year/type changes and resets pagination", async () => { defaults(); url("?page=3"); mount(); await screen.findByRole("table"); fireEvent.change(screen.getByLabelText("Year"), { target: { value: "2027" } }); fireEvent.change(screen.getByLabelText("Leave Type"), { target: { value: typeId } }); expect(navigationMock.replace).toHaveBeenLastCalledWith(`/reports?year=2027&leave_type_id=${typeId}`, { scroll: false }); });
  it("switches tabs while preserving compatible filters and resetting dates/status/page", async () => { defaults(); url(`?tab=applications&year=2025&page=3&status=PENDING&leave_type_id=${typeId}&from_date=2025-01-01`); mount("ADMINISTRATOR"); await screen.findByRole("table"); await userEvent.click(screen.getByRole("button", { name: "Utilization" })); expect(navigationMock.replace).toHaveBeenLastCalledWith(`/reports?tab=utilization&year=2025&leave_type_id=${typeId}`, { scroll: false }); await userEvent.click(screen.getByRole("button", { name: "Holidays" })); expect(navigationMock.replace).toHaveBeenLastCalledWith("/reports?tab=holidays&year=2025", { scroll: false }); });
  it("restores selected year/employee/type/department and requests one server page", async () => { defaults(); url(); const result = mount("ADMINISTRATOR"); await screen.findByRole("table"); let query = new URLSearchParams(); server.use(http.get(`${origin}/reports/leave-summary`, ({ request }) => { query = new URL(request.url).searchParams; return HttpResponse.json({ year: 2025, items: [], total: 105, page: 3, page_size: 50 }); })); url(`?year=2025&employee_id=${employeeId}&leave_type_id=${typeId}&department_id=${identity.department.department_id}&page=3&page_size=50`); result.rerender(<ReportsScreen/>); await screen.findByText("No balances on this page."); expect(query.get("employee_id")).toBe(employeeId); expect(query.get("department_id")).toBe(identity.department.department_id); expect(query.get("leave_type_id")).toBe(typeId); expect(query.get("page")).toBe("3"); expect(query.get("page_size")).toBe("50"); expect(screen.getByRole("button", { name: "Previous" })).toBeEnabled(); expect(screen.getByRole("button", { name: "Next" })).toBeDisabled(); expect(screen.getByLabelText("Year")).toHaveValue("2025"); });
  it("shows historical selected type fallback and sends dates/status for history", async () => { defaults(); url(`?tab=applications&leave_type_id=${employeeId}&from_date=2026-10-01&to_date=2026-10-31&status=APPROVED`); let query = new URLSearchParams(); server.use(http.get(`${origin}/leave/applications`, ({ request }) => { query = new URL(request.url).searchParams; return HttpResponse.json({ items: [], total: 0, page: 1, page_size: 20 }); })); mount(); await screen.findByText("No applications match this year and these filters."); expect(screen.getByRole("option", { name: "Selected historical leave type" })).toBeVisible(); expect(query.get("scope")).toBe("own"); expect(query.get("from_date")).toBe("2026-10-01"); expect(query.get("to_date")).toBe("2026-10-31"); expect(query.get("status")).toBe("APPROVED"); });
  it("shows loading then empty state and resets filters within current view", async () => { defaults(); url("?tab=utilization&year=2025"); let release!: () => void; const waiting = new Promise<void>(resolve => { release = resolve; }); server.use(http.get(`${origin}/reports/leave-summary`, async () => { await waiting; return HttpResponse.json({ items: [], total: 0, page: 1, page_size: 20, year: 2025 }); })); mount("ADMINISTRATOR"); expect(await screen.findByText("Loading your information…")).toBeVisible(); release(); await screen.findByText("No leave balances match this year and these filters."); await userEvent.click(screen.getByRole("button", { name: "Clear filters" })); expect(navigationMock.replace).toHaveBeenLastCalledWith("/reports?tab=utilization", { scroll: false }); });
  it("uses safe errors/retry without showing partial report", async () => { defaults(); url(); server.use(http.get(`${origin}/reports/leave-summary`, () => HttpResponse.json({ error: { code: "SERVER_ERROR", message: "unsafe SQL", details: null } }, { status: 500 }))); mount(); expect(await screen.findByRole("alert")).not.toHaveTextContent("unsafe SQL"); expect(screen.queryByRole("table")).toBeNull(); defaults(); await userEvent.click(screen.getByRole("button", { name: "Retry" })); expect(await screen.findByRole("table")).toBeVisible(); });
  it("handles 403 without exposing scoped data", async () => { defaults(); url(); server.use(http.get(`${origin}/reports/leave-summary`, () => HttpResponse.json({ error: { code: "FORBIDDEN", message: "Private", details: null } }, { status: 403 }))); mount(); expect(await screen.findByText("You don't have permission to view this page.")).toBeVisible(); expect(screen.queryByRole("table")).toBeNull(); });
  it("invalidates loaded summary reports after existing report invalidation", async () => { defaults(); url(); let calls = 0; server.use(http.get(`${origin}/reports/leave-summary`, () => { calls++; return HttpResponse.json({ items: [balance], year: 2026, total: 1, page: 1, page_size: 20 }); })); const { client } = mount(); await screen.findByRole("table"); await client.invalidateQueries({ queryKey: ["reports"] }); await waitFor(() => expect(calls).toBe(2)); await userEvent.click(screen.getByRole("button", { name: "Refresh report" })); await waitFor(() => expect(calls).toBe(3)); });
  it("displays holiday empty and count failures without inventing totals", async () => { defaults([], [], []); url("?tab=holidays"); const result = mount("ADMINISTRATOR"); await screen.findByText("No holidays in this year."); server.use(http.get(`${origin}/leave/applications`, ({ request }) => { const p = new URL(request.url).searchParams; return p.get("page_size") === "1" ? HttpResponse.json({ error: { code: "SERVER_ERROR", message: "safe", details: null } }, { status: 500 }) : HttpResponse.json({ items: [], total: 0, page: 1, page_size: 20 }); })); url("?tab=applications"); result.rerender(<ReportsScreen/>); await screen.findByText("No applications match this year and these filters."); expect(await within(screen.getByRole("region", { name: "Application status summary" })).findByRole("alert")).toBeVisible(); expect(within(screen.getByRole("region", { name: "Application status summary" })).queryByRole("heading", { name: "PENDING" })).toBeNull(); });
});
