"use client";
import Link from "next/link";
import { useDashboard } from "@/hooks/use-employee";
import { useLeaveYear } from "@/hooks/use-leave-year";
import { useAuth } from "@/hooks/use-auth";
import { calendarDate, leaveDays } from "@/lib/format";
import { QueryError, QueryLoading } from "@/components/common/QueryState";
import { YearSelect } from "@/components/common/YearSelect";
import { ManagerDashboardPanel } from "./ManagerDashboardPanel";
const counters = [{ key: "allocated", label: "Allocated" }, { key: "carried_forward", label: "Carried Forward" }, { key: "used", label: "Used" }, { key: "pending", label: "Pending" }, { key: "available", label: "Available" }] as const;
export function EmployeeDashboard() {
  const { user } = useAuth(); const selection = useLeaveYear(); const query = useDashboard(selection.year); const data = query.data;
  return <section className="max-w-6xl space-y-6"><header className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm text-slate-600">Your workspace</p><h1 className="text-3xl font-semibold">Welcome, {user?.name}</h1>
    <p className="mt-2 text-sm text-slate-600">{user?.employee_code} · {user?.department.name} · {user?.business_today && calendarDate(user.business_today)} ({user?.organization_timezone})</p></div><YearSelect {...selection} /></header>
    {user && user.role !== "EMPLOYEE" && <ManagerDashboardPanel/>}
    {selection.year === null ? <p role="alert">Enter a year between 1900 and 9999, or select a year above.</p> : query.isPending ? <QueryLoading /> : query.isError ? <QueryError error={query.error} retry={() => void query.refetch()} /> : data && <>
      <section aria-labelledby="totals-title"><h2 id="totals-title" className="mb-3 text-xl font-semibold">Leave totals · {data.year}</h2><dl className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">{counters.map(field => <div key={field.key} className="rounded-lg border border-slate-200 bg-white p-4"><dt className="text-sm text-slate-600">{field.label}</dt><dd className="mt-2 text-2xl font-semibold">{leaveDays(data.leave_totals[field.key])}</dd></div>)}</dl></section>
      <section aria-labelledby="balances-title"><div className="mb-3 flex flex-wrap justify-between gap-2"><h2 id="balances-title" className="text-xl font-semibold">Your leave balances</h2><Link href={`/leave/balance?year=${data.year}`} className="text-sm font-medium text-blue-700 underline">View detailed balances</Link></div>
        {data.leave_balances.length === 0 ? <p className="rounded-lg border border-slate-200 bg-white p-5">No leave balances have been allocated for {data.year}. Contact your administrator.</p> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.leave_balances.map(balance => <article key={balance.balance_id} className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-semibold">{balance.leave_type_name}</h3><dl className="mt-4 grid grid-cols-2 gap-3">{counters.map(field => <div key={field.key}><dt className="text-sm text-slate-600">{field.label}</dt><dd className={field.key === "available" ? "text-xl font-bold text-blue-800" : "font-medium"}>{leaveDays(balance[field.key])}</dd></div>)}</dl>{balance.available === 0 && <p className="mt-3 text-sm text-slate-500">No balance left</p>}</article>)}</div>}</section>
      <section aria-labelledby="quick-title" className="rounded-lg border border-slate-200 bg-white p-5"><h2 id="quick-title" className="font-semibold">Quick actions</h2><div className="mt-3 flex flex-wrap gap-3"><Link href="/profile" className="rounded border border-slate-300 px-3 py-2 text-sm">My Profile</Link><Link href={`/leave/balance?year=${data.year}`} className="rounded border border-slate-300 px-3 py-2 text-sm">Leave Balance</Link><Link href="/leave/apply" className="rounded border border-slate-300 px-3 py-2 text-sm">Apply Leave</Link></div></section>
      <div className="grid gap-6 lg:grid-cols-2"><section aria-labelledby="recent-title" className="rounded-lg border border-slate-200 bg-white p-5"><h2 id="recent-title" className="text-xl font-semibold">Recent applications</h2><p className="mt-2 text-sm text-slate-600">Pending applications in {data.year}: <strong>{data.pending_application_count}</strong></p>
        {data.recent_applications.length === 0 ? <p className="mt-4 text-slate-600">No leave applications yet.</p> : <ul className="mt-4 divide-y divide-slate-200">{data.recent_applications.map(item => <li key={item.application_id} className="py-3"><Link href={`/leave/applications/${item.application_id}`} className="font-medium text-blue-700 underline">{item.leave_type_name} · {item.status}</Link><p className="text-sm text-slate-600">{calendarDate(item.from_date)} – {calendarDate(item.to_date)} · {leaveDays(item.number_of_days)} days</p></li>)}</ul>}</section>
      <section aria-labelledby="holidays-title" className="rounded-lg border border-slate-200 bg-white p-5"><h2 id="holidays-title" className="text-xl font-semibold">Upcoming holidays</h2>{data.upcoming_holidays.length === 0 ? <p className="mt-4 text-slate-600">No upcoming holidays have been published.</p> : <ul className="mt-4 divide-y divide-slate-200">{data.upcoming_holidays.map(holiday => <li key={holiday.holiday_id} className="py-3"><p className="font-medium">{holiday.name}{holiday.is_optional ? " (Optional)" : ""}</p><p className="text-sm text-slate-600">{calendarDate(holiday.holiday_date)}</p></li>)}</ul>}</section></div>
      <p className="text-sm text-slate-600">Unread notifications: <strong>{data.unread_notification_count}</strong></p>
      {user?.role === "MANAGER" && data.manager_summary === null && <p className="text-sm text-slate-600">Team summary is not available yet.</p>}
      {user?.role === "ADMINISTRATOR" && data.admin_summary === null && <p className="text-sm text-slate-600">Organization summary is not available yet.</p>}
    </>}
  </section>;
}
